# The URL the site will be built for
base_url = "https://web.jhx.me"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = false

[markdown]
render_emoji = false

[markdown.highlighting]
theme = "catppuccin-mocha"

[languages.es]
generate_feeds = true

[languages.es.translations]
footer_text = "Este sito web fue creado por un Humano."

[translations]
footer_text = "This website was created by a Human."

[extra]
# Put all your custom variables here

